### ISSUE TITLE
Error paramiko

### ISSUE THREAD

**Issue by dpatrongomez** [thelinuxchoice/pyRAT#2]
`[+] Payload name (Default: pyRAT ): 
[+] PyRAT credentials config 
[+] Choose Username (Default: pyRAT ): 
[+] Choose Password (Default: CaptainHook ): 
[+] Choose Port1 to reverse connection (Default: 2825 ): 
[+] Choose Port 2 (Default: 3015 ): 
[+] Please wait, converting python payload to exe file... Done!
[+] Starting server http://serveo.net:2825
[+] Starting server http://serveo.net:3015

[+] Send the direct link to target: https://tracto.serveo.net/pyRAT.zip 
[+] Or using tinyurl: ERROR 

[+] Starting listener...
Traceback (most recent call last):
  File "pyRAT-server.py", line 2, in <module>
    import paramiko
ImportError: No module named paramiko`

**Comment by thelinuxchoice** [comment]
install paramiko module: python -m pip install paramiko
